### ISSUE TITLE
Feature: Button to automate setting time

### ISSUE THREAD

**Issue by StLolek** [Kamyil/worktimer2#3]
### Current behavior
There is only one possibility for setting times, and that is to do it by hand.

### Suggested solution
Add a button next to every time input that, on click, sets the time to current.

### Additional context
In my opinion, a button like this is very useful when you finish a task and want to quickly set the current time as the end time.

**Comment by Rajveer07** [comment]
could you elaborate this issue

**Comment by StLolek** [comment]
PR #6
