### ISSUE TITLE
Improvement: Automatically saving to localStorage

### ISSUE THREAD

**Issue by StLolek** [Kamyil/worktimer2#4]
### Current behavior
Automatically saving works only on interval.

### Suggested solution
Saving can be done when user add new task, to save previously added tasks. 
Additionally adding new task can start new interval to save the data of new task in some time (after time to setup a new task).

**Comment by Kamyil** [comment]
Thanks for opening the issue!

With this PR I've added saving data to localStorage on save, adding new task and adding a break (in addition to current interval)  


https://github.com/Kamyil/worktimer2/pull/5/files#diff-bf30edbb3a5817c3524d0e22f5fc742d46b3eafc1b1825dadb2303ec4d0989f4
